'use client'
import {createContext,useContext,useState}from'react'
export type Lang='Marathi'|'Hindi'|'English'
const copy={
 English:{home:'Home',shop:'Shop',contact:'Contact us',tag:'RESPECT FOR SACRED OFFERINGS, A BLESSING OF FRAGRANCE.',hero:'100% pure and sattvic incense, thoughtfully made from sacred Nirmalya offered in worship.',detail:'Sacred offerings, thoughtfully transformed into a pure and eco-conscious fragrance.',explore:'Explore Nirmal Shraddha',purpose:'OUR PURPOSE',storyTitle:'Nothing sacred should go to waste.',story:'For the past 10 years, Nirmal Youth Foundation has been working towards environmental conservation by collecting Nirmalya — sacred floral offerings — during festivals such as Ganpati and Navratri.',story2:'Instead of being discarded into rivers and waterways where they can add to pollution, these sacred flowers are respectfully collected and given a meaningful second life.',process:'Through a scientific and systematic process, they are transformed into NIRMAL SHRADDHA — an eco-friendly incense stick that preserves the fragrance of faith and devotion.',impact:'SACRED FLOWERS, SAVED FROM WASTE',impactTitle:'An offering deserves a better ending.',impactText:'Flowers offered in devotion should not become a burden on our waterways. We collect Nirmalya with care, then transform it into a fragrance for everyday rituals.',collection:'THE COLLECTION',collectionTitle:'Six expressions. One purpose.',collectionText:'Explore the range of premium fragrances from Nirmal Shraddha.',ritual:'A RITUAL, REIMAGINED',ritualTitle:'What begins as an offering becomes a fragrance of faith.',ritualText:'Nirmal Shraddha carries forward the emotion behind every offering — while giving nature a little more care.',discover:'Discover the collection'},
 Marathi:{home:'मुख्यपृष्ठ',shop:'उत्पादने',contact:'संपर्क',tag:'निर्माल्याचा सन्मान, सुगंधाचे वरदान.',hero:'देव चरणी अर्पण झालेल्या पवित्र निर्माल्यापासून बनवलेली १००% शुद्ध व सात्त्विक अगरबत्ती.',detail:'पवित्र अर्पणांचा विचारपूर्वक, शुद्ध आणि पर्यावरणपूरक सुगंधात पुनर्वापर.',explore:'निर्मल श्रद्धा जाणून घ्या',purpose:'आमचा उद्देश',storyTitle:'पवित्र गोष्ट कधीही वाया जाऊ नये.',story:'गेल्या १० वर्षांपासून निर्मल यूथ फाऊंडेशन गणपती, नवरात्री यांसारख्या उत्सवांमध्ये निर्माल्य संकलित करून पर्यावरण संवर्धनाचे कार्य करत आहे.',story2:'नद्या व जलमार्गांमध्ये टाकून प्रदूषण वाढवण्याऐवजी, ही पवित्र फुले आदराने संकलित करून त्यांना अर्थपूर्ण दुसरे आयुष्य दिले जाते.',process:'शास्त्रोक्त व वैज्ञानिक प्रक्रियेद्वारे या निर्माल्याचा पुनर्वापर करून तयार होते निर्मल श्रद्धा — श्रद्धेचा सुगंध जपणारी पर्यावरणपूरक अगरबत्ती.',impact:'पवित्र फुले, कचऱ्यापासून वाचवलेली',impactTitle:'प्रत्येक अर्पणाला चांगला शेवट मिळायला हवा.',impactText:'श्रद्धेने अर्पण केलेली फुले जलमार्गांवर ओझे बनू नयेत. आम्ही निर्माल्य काळजीपूर्वक संकलित करून रोजच्या उपासनेसाठी सुगंधात रूपांतरित करतो.',collection:'उत्पादन संग्रह',collectionTitle:'सहा सुगंध. एकच उद्देश.',collectionText:'निर्मल श्रद्धाच्या प्रीमियम सुगंधांचा संग्रह जाणून घ्या.',ritual:'पुनर्कल्पित उपासना',ritualTitle:'अर्पणापासून सुरू झालेला प्रवास श्रद्धेच्या सुगंधात बदलतो.',ritualText:'निर्मल श्रद्धा प्रत्येक अर्पणाची भावना जपते आणि निसर्गाची अधिक काळजी घेते.',discover:'संग्रह पहा'},
 Hindi:{home:'होम',shop:'उत्पाद',contact:'संपर्क करें',tag:'निर्माल्य का सम्मान, सुगंध का वरदान।',hero:'देव चरणी अर्पण किए गए पवित्र निर्माल्य से बनी १००% शुद्ध व सात्त्विक अगरबत्ती।',detail:'पवित्र अर्पणों को सोच-समझकर शुद्ध और पर्यावरण-सचेत सुगंध में बदला गया है।',explore:'निर्मल श्रद्धा देखें',purpose:'हमारा उद्देश्य',storyTitle:'कुछ भी पवित्र व्यर्थ नहीं जाना चाहिए।',story:'पिछले 10 वर्षों से निर्मल यूथ फाउंडेशन गणपति और नवरात्रि जैसे उत्सवों में निर्माल्य एकत्र कर पर्यावरण संरक्षण का कार्य कर रहा है।',story2:'नदियों और जलमार्गों में फेंककर प्रदूषण बढ़ाने के बजाय, इन पवित्र फूलों को आदरपूर्वक एकत्र किया जाता है और एक सार्थक नया जीवन दिया जाता है।',process:'वैज्ञानिक और व्यवस्थित प्रक्रिया द्वारा इन्हें निर्मल श्रद्धा में बदला जाता है — आस्था और भक्ति की सुगंध को संजोए एक पर्यावरण-अनुकूल अगरबत्ती।',impact:'पवित्र फूल, कचरे से बचाए गए',impactTitle:'हर अर्पण का एक बेहतर अंत होना चाहिए।',impactText:'भक्ति में चढ़ाए फूल हमारे जलमार्गों पर बोझ नहीं बनने चाहिए। हम निर्माल्य को संभालते हैं और उसे रोज़ की पूजा की सुगंध में बदलते हैं।',collection:'संग्रह',collectionTitle:'छह अभिव्यक्तियाँ। एक उद्देश्य।',collectionText:'निर्मल श्रद्धा की प्रीमियम सुगंधों का संग्रह देखें।',ritual:'एक नया अनुष्ठान',ritualTitle:'जो अर्पण से शुरू होता है, वह आस्था की सुगंध बनता है।',ritualText:'निर्मल श्रद्धा हर अर्पण की भावना को आगे बढ़ाती है और प्रकृति की अधिक देखभाल करती है।',discover:'संग्रह देखें'}
} as const
type Copy=Record<keyof typeof copy.English,string>
const C=createContext<{lang:Lang,setLang:(l:Lang)=>void;t:Copy}>({lang:'Marathi',setLang:()=>{},t:copy.Marathi})
export function LanguageProvider({children}:{children:React.ReactNode}){const[lang,setLang]=useState<Lang>('Marathi');return <C.Provider value={{lang,setLang,t:copy[lang]}}>{children}</C.Provider>}
export const useLanguage=()=>useContext(C)
